packages/graphin-site/gatsby-config.js
packages/graphin-site/package.json

修复网站搜索。antvis/gatsby-theme-antv#79
https://github.com/algolia/docsearch-configs/blob/master/configs/antv_graphin.json

docs: 🔍 Add algolia docsearchOptions

---

packages/graphin/src/controller/init.ts

This PR will allow the users to add custom G6 behavior modes.

fix: Support multiple behavior modes closes #62

---

packages/graphin/src/utils/Tree.ts
packages/graphin/src/utils/mock.ts

feature: add tree for mock

---

packages/graphin/src/types.ts

fix: support user defined property in date props

---

README.md

fix: readme npm command error

---

packages/graphin-components/src/components/legend/__tests__/index.test.tsx
packages/graphin-site/examples/advanced/node-expand/demo/ForceWithoutAnimation.jsx
packages/graphin-site/examples/advanced/node-expand/demo/meta.json
packages/graphin-site/examples/layout/force/demo/ForceWithoutAnimation.jsx
packages/graphin-site/examples/layout/force/demo/meta.json
packages/graphin/package.json
packages/graphin/src/layout/basic/force.ts
packages/graphin/src/layout/force/ForceLayout.ts

修复力导动画关闭失效的bug
TODO：
- g在力导布局下的渲染性能问题：e.applyAttrsToContext
- 力导的分层计算，解决计算性能问题（在无动画情况下尤为重要）
- Force Tweak的文档整理，有动画与无动画，都是非常重要的特性，针对不同的业务场景

Force laout without animate

---

packages/graphin/src/events/change-zoom.ts
packages/graphin/src/perf/optimizeDrawing.ts
packages/graphin/src/shape/graph-studio/CircleNode.ts

🐛fix(KeyShape) : fix KeyShape optimize issue

---

packages/graphin/src/Graphin.tsx
packages/graphin/src/controller/layout/index.tsx
packages/graphin/src/controller/state.ts
packages/graphin/src/shape/render/compiler.ts
packages/graphin/src/types.ts

feat: 沉淀知识图谱在graphin上的改动

---

packages/graphin-components/README.md
packages/graphin-components/src/ContextMenu/index.en-US.md
packages/graphin-components/src/CreateEdge/index.en-US.md
packages/graphin-components/src/FindPathPanel/index.en-US.md
packages/graphin-components/src/FindPathPanel/index.md
packages/graphin-components/src/FishEye/index.en-US.md
packages/graphin-components/src/Hull/index.en-US.md
packages/graphin-components/src/LayoutSelector/index.en-US.md
packages/graphin-components/src/Legend/index.en-US.md
packages/graphin-components/src/MapMode/index.en-US.md
packages/graphin-components/src/MiniMap/index.en-US.md
packages/graphin-components/src/Sheetbar/index.en-US.md
packages/graphin-components/src/SnapshotGallery/index.en-US.md
packages/graphin-components/src/Statistic/index.en-US.md
packages/graphin-components/src/TableMode/index.en-US.md
packages/graphin-components/src/Timebar/index.en-US.md
packages/graphin-components/src/Toolbar/index.en-US.md
packages/graphin-components/src/Tooltip/index.en-US.md

Add English translation for components and main Readme.
Did not add one for RedoUndo as it is listed as TodoUndo in the folder. Redo is the correct word. Todo is 去做

 docs: add english translation

---

packages/graphin-components/src/ContextMenu/demos/ContextMenu.tsx
packages/graphin/docs/render/element/graphin-circle.tsx
packages/graphin/docs/render/element/index.md
packages/graphin/package.json
packages/graphin/src/Graphin.tsx
packages/graphin/src/consts.ts
packages/graphin/src/index.ts
packages/graphin/src/shape/graphin-circle.ts
packages/graphin/src/shape/index.ts
packages/graphin/src/shape/react/Circle.tsx
packages/graphin/src/shape/react/Node.tsx
packages/graphin/src/shape/react/Text.tsx
packages/graphin/src/typings/type.ts
packages/graphin/src/utils/mock.ts

feat: add Graphin circle shape

---

packages/graphin/src/Graphin.tsx
packages/graphin/src/types.ts

修复布局切换后currentData取值, 优化布局切换后是否重新fitview由layoutChangeFitview参数控制

feat: 修复布局切换后currentData取值, 优化布局切换后是否重新fitview由layoutChangeFitview参数控制

---

packages/graphin-icons/src/demos/index.en-US.md
packages/graphin/docs/behaviros/index.en-US.md
packages/graphin/docs/layout/combo/index.en-US.md
packages/graphin/docs/layout/network/index.en-US.md
packages/graphin/docs/layout/tree/index.en-US.md
packages/graphin/docs/render/theme/index.en-US.md

- Fixed some syntax errors
- Unified some formats

docs: optimize the docs

---

packages/dumi-theme-graphin/package.json
packages/dumi-theme-graphin/src/components/Banner/index.tsx
packages/dumi-theme-graphin/src/layout.tsx
packages/graphin-components/package.json
packages/graphin/package.json
packages/graphin/src/Graphin.tsx

-Use `lodash-es/cloneDeep` to replace `utils/deepMix` to solve the error when the user uses immutable data.

chore: release graphin version 2.0.1

---

packages/graphin/docs/render/update/index.md
packages/graphin/docs/render/update/node.tsx
packages/graphin/docs/render/update/state.tsx
packages/graphin/package.json
packages/graphin/src/shape/graphin-circle.ts
packages/graphin/src/shape/utils.ts
packages/graphin/src/utils/index.ts

Add the feature of updating node badges style

chore: release version 2.0.3

---

packages/graphin/src/shape/utils.ts

#237 
when label position is center, the offset is not working.

fix: update labelPosition with offset when position is center

---

packages/graphin/docs/render/element/node.md

fix: fix spell mistake

---

packages/graphin/docs/render/element/node.en-US.md

fix: fix spell mistake?

---

packages/graphin/docs/render/status/demos/edge-status.tsx
packages/graphin/docs/render/status/index.md

docs: add edge status demo

---

packages/graphin-components/src/ContextMenu/Menu.tsx
packages/graphin/docs/behaviors/demos/drag-force-node.tsx
packages/graphin/docs/render/status/demos/edge-status.tsx
packages/graphin/docs/render/status/demos/index.less
packages/graphin/docs/render/status/index.en-US.md
packages/graphin/docs/render/status/index.md
packages/graphin/package.json
packages/graphin/src/behaviors/DragNodeWithForce.tsx

- Update labelPosition with offset when position is center 
- Update DragForceNode Behaviors to support layout changes
- Add Set Status demos

chore: release graphin 2.0.6

---

packages/graphin-components/src/LayoutSelector/demos/LayoutSelectorDemo.tsx

line149 函数注释与实际参数不一致
changedFiled -> changedField

docs: fix typo [changedFiled]

---

packages/graphin-graphscope/package.json
packages/graphin-graphscope/src/index.css

fix: global background color

---

packages/graphin-components/src/Grid/api-docs.ts
packages/graphin-components/src/Grid/demos/customImg.tsx
packages/graphin-components/src/Grid/demos/index.tsx
packages/graphin-components/src/Grid/index.en-US.md
packages/graphin-components/src/Grid/index.less
packages/graphin-components/src/Grid/index.md
packages/graphin-components/src/Grid/index.tsx
packages/graphin-components/src/index.ts

feat: Grid插件
feat: 撤回graphin-components依赖
feat: add Grid

feat: add grid plugin

---

packages/graphin-components/src/Combo/api-docs.ts
packages/graphin-components/src/Combo/demos/Simple.tsx
packages/graphin-components/src/Combo/index.en-US.md
packages/graphin-components/src/Combo/index.md
packages/graphin-components/src/Combo/index.tsx

add  combo component

---

package.json
packages/graphin-components/package.json
packages/graphin-components/src/index.ts
packages/graphin/package.json
packages/graphin/src/layout/force/ForceLayout.ts
packages/graphin/src/layout/force/ForceNBody.ts

* implement new `computeCoulombsLaw` method using quadtree and Barnes-Hut approximation
* reduce computing complexity from O(N^2) to O(NlogN)

perf: ⚡️ new force computing method for force directed layout

---

packages/graphin/docs/layout/dynamic-layout/demos/graphin-force.tsx
packages/graphin/package.json
packages/graphin/src/layout/force/ForceNBody.ts
packages/graphin/src/layout/utils/graph.ts

fixed weird jitter in force layout

fix: 🐛 force layout not converge

---

packages/graphin/docs/quick-start/index.md

fix: 文档文案错误，删除多余字符

---

packages/graphin/package.json
packages/graphin/src/layout/force/ForceLayout.ts
packages/graphin/src/layout/utils/graph.ts

perf force layout centripetalOptions

feat: perf graphin-force centripetalOptions

---

packages/graphin/docs/layout/leaf-cluster/demos/complex.tsx
packages/graphin/docs/layout/leaf-cluster/demos/simple.tsx
packages/graphin/docs/layout/leaf-cluster/index.en-US.md
packages/graphin/docs/layout/leaf-cluster/index.md
packages/graphin/package.json
packages/graphin/src/layout/force/ForceLayout.ts
packages/graphin/src/layout/utils/graph.ts

feat: graphin-force leaf cluster

---

packages/graphin/package.json
packages/graphin/src/layout/force/ForceLayout.ts

feat: distanceThresholdMode for graphin-force to control the termination

feat: distanceThresholdMode for graphin-force to control the termination

---

packages/graphin/package.json
packages/graphin/src/layout/force/ForceLayout.ts

fix: graphin-force renderNodes清空

---

packages/graphin/docs/layout/combo-combined-layout/demos/combo-combined-data2.tsx
packages/graphin/docs/layout/combo-combined-layout/index.md

docs: complex demo combo and interactions

docs: complex demo combo and interactions

---

packages/graphin/package.json
packages/graphin/src/Graphin.tsx

fix: dragNodes with nonexistent node

fix: dragNodes with nonexistent node

---

packages/graphin/package.json
packages/graphin/src/layout/force/ForceLayout.ts

perf: speed up the graphin-force

perf: speed up the graphin-force

---

packages/graphin/src/Graphin.tsx
packages/graphin/src/layout/force/ForceLayout.ts
packages/graphin/src/layout/utils/graph.ts

fix: 力导计算 degree 信息放到前面

---

packages/graphin/docs/render/element/demos/edge-default.tsx
packages/graphin/package.json
packages/graphin/src/shape/graphin-line.ts

feat: fix loop-edge label background bug

---

packages/graphin/src/components/Tooltip/getContainerStyles.tsx

fix: Fix a bug lead to a visible tooltip when not hovered

---

packages/graphin/src/shape/graphin-line.ts
packages/graphin/src/typings/type.ts

feat: 自环边箭头

---

packages/graphin/docs/interface/index.md
packages/graphin/package.json
packages/graphin/src/Graphin.tsx

Fix the problem of animation disappearing after layout switching

Pomelo 0811

---

packages/graphin/src/behaviors/DragNodeWithForce.tsx

fix: node layout property may not exist

fix: node layout property may not exist

---

packages/graphin/src/components/Tooltip/getContainerStyles.tsx
packages/graphin/src/components/Tooltip/index.tsx

- Added `auto`, `top-left`, `top-right`, `bottom-left` and `bottom-right` positions to tooltip. `auto` would automatically select the position based on the pointer location in the canvas
https://user-images.githubusercontent.com/7285903/176151230-92f101bf-6d20-44e1-ad90-d6ff5aa304c7.mp4

feat:  Automatically position tooltip

---

packages/graphin/src/components/Tooltip/index.tsx
packages/graphin/src/components/Tooltip/useTooltip.tsx

Allows the ability to change the delay of the the toolbar visibility (both hide/show) via a prop. If nothing is passed it will behave as before.
https://user-images.githubusercontent.com/7975925/203786902-8c7418d3-f29d-4ea6-9355-89e8b942b9e8.mp4
https://user-images.githubusercontent.com/7975925/203786911-53d8f5fb-a73d-402b-be85-6a56c241c8e9.mp4

feat: Added ability to customize tooltip delay

---

packages/graphin/package.json
packages/graphin/src/Graphin.tsx

feat: update version

---

README.md
README.zh-CN.md

- update docs 
- remove dingtalk

feat: update docs

---

packages/graphin/package.json
packages/graphin/src/utils/index.ts

* 解决工具方法 deepMix 和 cloneDeep 丢失的问题。从 lodash 中导出

fix: fix issue that lose deepMix and cloneDeep function

---

packages/graphin/package.json
packages/graphin/src/layout/utils/graph.ts
packages/graphin/src/utils/index.ts

* 移除 Utils 中的 lodash 方法导出
* 将 lodash-es 添加到 peerDependencies
关联 Issue: https://github.com/antvis/Graphin/issues/500

refactor: remove lodash utils export, and add lodash-es to peerDependencies

---

packages/graphin/package.json
packages/graphin/src/behaviors/index.tsx
packages/graphin/src/index.ts

feat: export useBehaviorHook

---

packages/graphin/package.json
packages/graphin/src/shape/graphin-line.ts

feat: supports state styles for custom shapes

feat: supports state styles for custom shapes

---

packages/graphin/src/shape/graphin-circle.ts

Update graphin-circle.ts for #507

---

packages/graphin/docs/render/update/node.tsx
packages/graphin/src/shape/graphin-circle.ts

fix badges render other style, such as visible、fillOpacity、opacity

fix: badges render style
