README.md, packages/graphin-site/gatsby-config.js, packages/graphin-site/package.json, packages/graphin-site/site/pages/GraphinStudio.zh.tsx, packages/graphin/README-cn.ZH.md, packages/graphin/README.md
https://github.com/antvis/antvis.github.io/issues/18
=> 🚀 graphin.antv.vision

.eslintrc.js, package.json, packages/graphin-site/docs/api/extend.en.md, packages/graphin-site/docs/api/extend.zh.md, packages/graphin/src/Graphin.tsx, packages/graphin/src/controller/layout/index.tsx, packages/graphin/src/types.ts
1. define getLayoutInfo's return type
2. "eslint-plugin-import" is broken after upgrade to 2.19.1, lock it temporarily.
=> define getLayoutInfo's return type

packages/graphin-studio/src/Extend/RectNodeShape.ts
fix 'highlight.dark' style not working issue when node state is dark
=> fix: extend ReactNodeShape dark style

packages/graphin-components/src/components/legend/__tests__/index.test.tsx, packages/graphin-components/src/components/legend/index.tsx
Resolves : [ #150 ](https://github.com/antvis/Graphin/issues/150)
**Previous State :** 
1. when props were updating  Legend was not updating. Here is a stackblitz to demonstrate that. 
https://stackblitz.com/edit/react-mv6hzc
2. There were no test written to test the legend.
**Resolution :** 
1. Now as props update the state of the Legend will also be updated. All the new props are not getting transferred to the state because of the addition of useEffect which will file if props.options get updated
2. New passing tests have been added with 100% coverage for Legend file.
=> fix: #150 (resolved)-legend not updating on props update

packages/graphin-components/src/components/toolbar/index.tsx, packages/graphin-components/src/components/toolbar/useZoom.ts
计入toolbar鼠标滚轮对于Zoom的影响
用graph?.getZoom()得到当前滚轮的ratio
避免操作情况出现：
1. 用户鼠标缩小或增大
2. 用toolbar 的 + / -  调节后， 图片跳回鼠标缩小或增大之前的 ratio
=> fix: toolbar zoom add parameters for mouse wheel 

packages/graphin/docs/render/theme/setting-ts.tsx, packages/graphin/src/index.ts
在业务的 Typescript 开发实践中，我们发现一些需要的 type 无法直接导出使用。因此，开此 PR 提议把以下 type 导出。
1. 导出 `IUserEdge` 和 `IUserNode` 与 `GraphinData` 一起使用
2. 导出 `ThemeType` 与 `theme` 变数一起使用
3. 导出 `Layout` 与 `layout` 变数一起使用
```tsx
import Graphin, { GraphinData, IUserNode, IUserEdge, ThemeType, Layout } from "@antv/graphin"; 
const data: GraphinData = Utils.mock(8).circle().graphin();
const theme: Partial<ThemeType> = { mode: 'light' }
const layout: Layout = { type: 'concentric' }; 
data.nodes.forEach((node: IUserNode) => console.log (node));
data.edges.forEach((edge: IUserEdge) => console.log (edge));
export default () => {
return (
<Graphin data={data} layout={layout} theme={theme} />
);
};
```
1. 移除了原本的 [`Layout`](https://github.com/antvis/Graphin/compare/master...CodesAreHonest:expose-necessary-types?diff=split&expand= …
=> 导出需要的Typescript类型

packages/graphin-components/package.json, packages/graphin/package.json, packages/graphin/src/Graphin.tsx
- update g6 version to 4.1.11
- remove lodash dependence
=> chore: 🎉  release graphin version 2.0.0-beta.15

package.json, packages/dumi-theme-graphin/package.json, packages/graphin-components/package.json, packages/graphin-graphscope/package.json, packages/graphin-site/package.json, packages/graphin-studio/package.json, packages/graphin/package.json
The current stable version of React is v17.
This packages cannot use project that needs React v17 because dependency has set to React v16.
(For example, Next.js stable version 10 needs react v17)
I've rewrite all React version in `package.json` under `packages` directory.
React v16 to v17 has no breaking change, no new features.
So I think there is no critical problem to upgrade v17.
https://reactjs.org/blog/2020/10/20/react-v17.html
I cannot resolve React version dependency of the independent package `@antv/gatsby-theme-antv` .
But I've found pull request that to upgrade React to v17.
https://github.com/antvis/gatsby-theme-antv/pull/282
So This pull request force to set `@antv/gatsby-theme-antv` dependency for `upgrade-deps` branch.
It should be fixed before merge.
So this pull request …
=> chore(🆙): Upgrade React to v17.0.1

packages/graphin/README.md
This PR fixes the link of `README-zh.CN.md` in `README`.
=> docs: fix link of README-zh.CN.md in README

packages/graphin-components/package.json, packages/graphin-components/src/CreateEdge/index.tsx, packages/graphin-components/src/FishEye/index.tsx, packages/graphin-components/src/Grid/index.tsx, packages/graphin-components/src/MiniMap/index.tsx, packages/graphin/package.json, packages/graphin/src/Graphin.tsx, packages/graphin/src/shape/graphin-circle.ts, packages/graphin/src/shape/graphin-line.ts, packages/graphin/src/theme/index.ts
- 修复组件卸载报错
- 新增Grid组件
- 移除 defaultNodeStyle 设置，仅传递 theme 数值，默认样式计算放在节点和边的注册流程中。
=> chore: release graphin 2.2.0 

packages/graphin/src/shape/graphin-line.ts
Fixes the label background by considering the offset
Before:
After:
=> fix: edge label background offset

packages/graphin/src/shape/graphin-circle.ts
Close https://github.com/antvis/Graphin/issues/271
The offset was not handled correctly for the text on a circular badge
Before:
After:
=> fix: badge with text

packages/graphin/src/shape/graphin-circle.ts
This allows to set up click events on badges with different behaviors depending on the badge that was clicked
```javascript
Graphin.registerBehavior('sampleBehavior', {
getEvents() {
return {
'badges-circle:mousedown': 'onClick'
};
},
onClick(evt) {
// prints node id and badge id
console.log(evt.item.getID(), evt.target.cfg?.id);
}
});
```
In the following video, I set up the badges with an id equal to the position (for simplicity)
https://user-images.githubusercontent.com/2861371/142420396-f53daf9f-b2aa-458c-b440-fa870f7cd0eb.mp4
=> feat: add id attribute to badges

packages/graphin/src/typings/type.ts
Example with a blue background
Opacity = 1 (default)
Opacity = 0.2
=> feat: support opacity in edge label background

packages/graphin/src/layout/index.ts
Prevent gforce layout from jittering by updating the nodes on every tick. Update the node positions at the end of layout.
Fixes #295 
<table>
<tr>
<td>
Before
https://user-images.githubusercontent.com/7285903/143027902-d929ebd0-ee1a-40c9-b27f-dce5793550fa.mp4
</td>
<td>
After
https://user-images.githubusercontent.com/7285903/143027891-89c0db83-b7c7-4d2b-80d5-3ac97d28ff72.mp4
</td>
</tr>
</table>
=> fix: Update positions at the end of gforce layout

packages/dumi-theme-graphin/package.json, packages/graphin-components/package.json, packages/graphin-graphscope/package.json, packages/graphin-icons/package.json, packages/graphin-studio/package.json, packages/graphin/package.json
Hi there!
This change adds the repository property to your package.json file(s). Having this available provides a number of benefits to security tooling. For example, it allows for greater trust by checking for signed commits, contributors to a release and validating history with the project. It also allows for comparison between the source code and the published artifact in order to detect attacks on authors during the publication process.
We validate that we're making a PR against the correct repository by comparing the metadata for the published artifact on [npmjs.com](www.npmjs.com) against the metadata in the package.json file in the repository.
This change is provided by a team at Microsoft -- we're happy to answer any questions you may have. (Members of this team include …
=> Update package.json to include the repository

packages/graphin/src/behaviors/ZoomCanvas.tsx, packages/graphin/src/typings/type.ts
Recently I added the animation support for zoom operations in G6, this is the last bit :)
Additionally, this makes the opacity parameter optional (I overlooked that in my previous PR)
=> Feat: support animation in ZoomCanvas behavior

packages/graphin/package.json, packages/graphin/src/utils/processEdges.ts
Using the `Utils.processEdges` function to process poly edges with an even count causes at least one of the edges to be a straight line as opposed to a curved edge. This PR fixes that. Below are some screenshots of the issue and its fix.
Before (with 2 edges)
After (with 2 edges)
Before (with 4 edges)
After (with 4 edges)
=> fix: straight line on even count poly edges

packages/graphin/docs/render/element/demos/node-animate.tsx
Changes to be committed:
modified:   packages/graphin/docs/render/element/demos/node-animate.tsx
This PR contains a simple fix to update a hoverable demo that was broken since v2.3.3 which removes the default "hoverable" behavior.
=> fix: Update broken demo since v2.3.3

packages/graphin/src/layout/index.ts
Since `graph.emit('afterlayout')` is being used [on layout end ](https://github.com/antvis/Graphin/blob/8e0fe869ce4dd5814ff51f9a58ed8d634be7adb7/packages/graphin/src/layout/index.ts#L190) for force layouts. It causes multiple emits.
=> fix: Fix multiple `afterlayout` emits

packages/graphin/src/components/Hull/index.tsx
更新图数据后，Hull组件updateData报错
https://codesandbox.io/s/zealous-dawn-t1h83t?file=/src/App.js
=> fix: 更新图数据后，Hull组件updateData报错

packages/graphin/src/utils/__tests__/processEdges.test.ts, packages/graphin/src/utils/processEdges.ts
On latest master, if I create 3 loop edges on single node, labels/edges were positioned on top of each other.
The part about loop edges was working fine on previous version and seems to be broken on `2.6.5`. So, I did the check and it seems to be the issue is with removal of `deepMix` usage on the latest master for processing edges (restored it).
If edge is loop, label position processed based on loop distance and initial offset based on default value for poly.
Did some rework on conditions and added the tests.
**BEFORE:**
**AFTER:**
There is the animation showing dynamically changed loop value. Label keeps its positioning based on loop.
=> Fixed loop edges positioning and labels for loop edges

packages/graphin/src/shape/graphin-line.ts
=> fix: Fix node size smaller than 16 producing NaN in Math.sqrt

packages/graphin/src/behaviors/ClickSelect.tsx
This PR enables edge selection in Behaviors.ClickSelect to complement this recent PR in G6: https://github.com/antvis/G6/pull/3601.
It's sufficient to add values to the default config to match the ones supplied in `click-select` [at this location](https://github.com/leonardodalinky/G6/blob/45c372d8b3b72020664f1cb0253775d3804347df/packages/pc/src/behavior/click-select.ts#L13-L15). Typescript types are automatically extracted from that default object using `typeof`.
=> Add selectable edges to Behaviors.ClickSelect

packages/graphin/docs/interface/index.en-US.md, packages/graphin/src/Graphin.tsx, packages/graphin/src/typings/type.ts
This PR adds support for the right-to-left [text direction](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) to support languages like Arabic or Hebrew.
Setting the `dir` attribute should be performed before the first `graph.render()` call, which is why I made this PR here on Graphin.
The added prop only includes values `'ltr' | 'rtl'`. While the `dir` attribute in normal HTML nodes also supports `'auto'`, that option doesn't seem to work in canvas in the few examples I tried.
It's also not supported by `<svg>` nodes, which is a possible target for a G6 renderer if I get it right, see the [direction](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/direction) attribute for SVG nodes.
- I didn't try the case for SVG, since it's not in my particular …
=> Add support for right-to-left text direction

packages/graphin/src/behaviors/BrushSelect.tsx
Related PR in G6: https://github.com/antvis/G6/pull/3972
This PR adds support for selecting combos using the "brush-select" behavior. A new "includeCombos" parameter is added (default = false) to explicitly enable this effect.
Combos are selected when their midpoint is included in the rectangular brush area (similarly to edges) - most obvious when the combo is expanded:
https://user-images.githubusercontent.com/16387428/193308128-a70a47b5-1578-48b5-9950-0e7b577b33ac.mp4
=> feat: add combo support in brush-select behavior

packages/graphin/src/shape/utils.ts
With this change we can update the opacity of a nodes icon like:
```javascript
const nodes = graph.getNodes();
const model = nodes[0].getModel() as NodeConfig;
graph.focusItems([nodes[0]], true, true);
if (model && model.style) {
model.style.icon.opacity = 0.25;
nodes[0].update(model);
}
```
Before:
https://user-images.githubusercontent.com/2861371/191519727-93d7d64a-05d1-46e1-9fe1-a8d0baa5163f.mp4
After:
https://user-images.githubusercontent.com/2861371/191519735-fad08dd4-4f09-4ad3-8738-fb9b7ab14cef.mp4
=> fix: passthrough opacity param for images

packages/graphin-components/src/ContextMenu/index.tsx
On first click `getBoundingClientRect()` returns `0` for height, due to the child elements not yet being rendered in the contextMenu. In return the correct offset of the context menu is not removed from `canvasY` when calculating the `y` value.
Before:
https://user-images.githubusercontent.com/7975925/164475620-debe3dfe-2866-4df6-9a7d-c5dc67c82600.mp4
After:
https://user-images.githubusercontent.com/7975925/164475945-3e65b389-25f2-4ddb-9819-57e151ea1c77.mp4
=> fix: Fixed issue with ContextMenu not positioning correctly on first click.

packages/graphin/src/shape/graphin-line.ts
修复status中设置样式不能影响label的背景元素
status: {
'label-background': {
opacity: 0
}
}
=> fix 边label背景不支持status

packages/graphin/src/components/Legend/Node.tsx
- fixed #471 
<Legend.Node />组件中如果绑定的type为'edge', 会触发edge没有getEdges方法的错误，导致在过滤edge的过程中只会匹配第一个匹配的边，后续的边无法匹配
=> fix: Legend doesn't work when BindType='edge'
